import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize, forkJoin, switchMap } from 'rxjs';
import { AgencyManagementApiService } from '../../core/api/manage-api.services';
import { Agency, AgencyInvitation, AgencyMember, AgencyRole } from '../../core/models/manage.models';
import { ToastService } from '../../core/services/toast.service';
import { ManageStatusComponent } from './manage-ui';

@Component({standalone:true,imports:[DatePipe,ReactiveFormsModule,ManageStatusComponent],template:`
<section class="workspace"><header class="page-head"><div><h1>Agency Team</h1><p>Invite team members and manage their access.</p></div><span class="count">{{members().length}} members</span></header>
@if(error()){<p class="error" role="alert">{{error()}}</p>}
@if(loading()){<div class="skeleton"></div>} @else if(agency();as a){
<section class="invite-card"><div><h2>Invite a team member</h2><p>Give a colleague secure access to your agency workspace.</p></div><form [formGroup]="form" (ngSubmit)="invite(a)"><label>Email address<input type="email" formControlName="email" placeholder="agent@example.com"/></label><label>Role<select formControlName="role"><option value="AGENT">Agent</option><option value="ADMIN">Admin</option></select></label><button class="primary" [disabled]="form.invalid||busy()">{{busy()?'Sending...':'Send Invite'}}</button></form></section>
<header class="section-head"><div><h2>Members ({{members().length}})</h2><p>People who can work in this agency.</p></div></header><div class="members">@for(m of members();track m.id){<article class="member-card"><div class="avatar">@if(m.avatar){<img [src]="m.avatar" alt=""/>} @else {{{initials(m.name)}}}</div><div><h3>{{m.name}} @if(m.role==='OWNER'){<span class="owner">Owner</span>}</h3><p>{{m.email}}</p><small>{{m.role==='OWNER'?'Account owner · Owner role cannot be changed.':'Can manage agency listings.'}}</small></div>@if(m.role==='OWNER'){<span class="protected">Protected</span>} @else {<div class="member-actions"><select [value]="m.role" (change)="role(a,m,$any($event.target).value)"><option value="ADMIN">Admin</option><option value="AGENT">Agent</option></select><button class="danger" (click)="remove(a,m)">Remove</button></div>}</article>}</div>
<header class="section-head"><div><h2>Pending invitations ({{invitations().length}})</h2><p>Invited team members will appear here.</p></div></header>@if(invitations().length){<div class="invitations">@for(i of invitations();track i.id){<article><div><strong>{{i.email}}</strong><p>{{i.role}} · Sent invitation</p></div><div><sp-manage-status [status]="i.status"/><small>Expires {{i.expires_at|date:'mediumDate'}}</small></div></article>}</div>} @else {<section class="empty"><strong>No pending invitations.</strong><p>Invited team members will appear here.</p></section>}
} @else {<section class="empty"><h2>No agency found.</h2><p>Create or join an agency to manage its team.</p></section>}</section>`,styles:[`.workspace{display:grid;gap:1rem;max-width:1160px}.page-head,.section-head{display:flex;justify-content:space-between;gap:1rem;align-items:end}.page-head h1,.page-head p,.section-head h2,.section-head p,h3,p{margin:0}.page-head p,.section-head p,p,small{color:var(--slate)}.count,.owner,.protected{display:inline-flex;width:max-content;border-radius:999px;padding:.28rem .55rem;background:#e6f7ef;color:#17633b;font-size:.75rem;font-weight:850}.invite-card{display:grid;grid-template-columns:1fr 1.5fr;gap:1rem;padding:1rem;border:1px solid var(--line);border-radius:1rem;background:#fff}.invite-card form{display:grid;grid-template-columns:1fr 140px auto;gap:.6rem;align-items:end}label{display:grid;gap:.3rem;font-size:.8rem;font-weight:850}input,select,button{min-height:42px;box-sizing:border-box;border:1px solid var(--line);border-radius:.55rem;padding:.6rem;background:#fff;font:inherit}.primary{border-color:var(--teal);background:var(--teal);color:#fff;font-weight:850}.error{padding:.75rem;border-radius:.55rem;background:#fff2f2;color:#9b2525}.members,.invitations{display:grid;gap:.7rem}.member-card,.invitations article{display:grid;grid-template-columns:48px 1fr auto;gap:.8rem;align-items:center;padding:.85rem;border:1px solid var(--line);border-radius:1rem;background:#fff}.avatar{display:grid;place-items:center;width:48px;height:48px;overflow:hidden;border-radius:50%;background:#e6f7f1;color:var(--teal);font-weight:900}.avatar img{width:100%;height:100%;object-fit:cover}.member-card h3{font-size:1rem}.member-card p{margin:.2rem 0}.member-actions{display:flex;gap:.4rem}.danger{color:#9b2525}.protected{background:#edf0f0;color:#60706f}.invitations article{grid-template-columns:1fr auto}.invitations article>div:last-child{display:grid;justify-items:end;gap:.3rem}.empty{display:grid;justify-items:center;gap:.35rem;padding:2.4rem 1rem;border:1px solid var(--line);border-radius:1rem;background:#fff;text-align:center}.skeleton{height:220px;border-radius:1rem;background:var(--mist)}@media(max-width:700px){.page-head,.section-head,.invite-card{display:grid}.invite-card form{grid-template-columns:1fr}.member-card{grid-template-columns:48px 1fr}.member-actions,.protected{grid-column:1/-1}.invitations article{grid-template-columns:1fr}.invitations article>div:last-child{justify-items:start}}`]
})
export class AgencyTeamComponent{private api=inject(AgencyManagementApiService);private fb=inject(FormBuilder);private toast=inject(ToastService);loading=signal(true);busy=signal(false);error=signal('');agency=signal<Agency|null>(null);members=signal<AgencyMember[]>([]);invitations=signal<AgencyInvitation[]>([]);form=this.fb.nonNullable.group({email:['',[Validators.required,Validators.email]],role:['AGENT' as AgencyRole,Validators.required]});constructor(){this.load()}initials(name:string){return name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}load(){this.loading.set(true);this.error.set('');this.api.mine().pipe(switchMap(items=>{const agency=items[0];this.agency.set(agency||null);return agency?forkJoin({members:this.api.members(agency.id),invitations:this.api.invitations(agency.id)}):forkJoin({members:[],invitations:[]})}),finalize(()=>this.loading.set(false))).subscribe({next:({members,invitations})=>{this.members.set(members);this.invitations.set(invitations)},error:()=>this.error.set("Couldn't load this page.")})}invite(a:Agency){if(this.form.invalid)return;this.busy.set(true);this.error.set('');this.api.invite(a.id,this.form.getRawValue()).pipe(finalize(()=>this.busy.set(false))).subscribe({next:invite=>{this.invitations.update(items=>[invite,...items]);this.toast.show({kind:'success',title:'Invitation sent'});this.form.reset({email:'',role:'AGENT'})},error:e=>this.error.set(e?.error?.message||e?.error?.detail||'The invitation could not be sent. Check whether this person is already a member or has a pending invitation.')})}role(a:Agency,m:AgencyMember,role:AgencyRole){this.api.updateRole(a.id,m.id,role).subscribe({next:()=>{this.toast.show({kind:'success',title:'Role updated'});this.load()},error:()=>this.error.set('Role could not be updated.')})}remove(a:Agency,m:AgencyMember){if(!confirm(`Remove ${m.name} from this agency?`))return;this.api.removeMember(a.id,m.id).subscribe({next:()=>{this.toast.show({kind:'success',title:'Member removed'});this.members.update(items=>items.filter(x=>x.id!==m.id))},error:()=>this.error.set('Member could not be removed.')})}}
